# Generated by Django 4.2 on 2023-05-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
